//! Evidence-labelled vftable metadata and raw slot access.
//! Slot calls remain the consumer's responsibility until a signature is unique.

use core::ffi::c_void;

#[derive(Clone, Copy, Debug)]
pub struct VTableInfo { pub name: &'static str, pub rva: u32, pub first_slot: usize, pub slot_count: usize, pub confidence: &'static str }

#[derive(Clone, Copy, Debug)]
pub struct VTableSlot { pub table_rva: u32, pub slot: u32, pub byte_offset: u32, pub target_rva: u32, pub target_id: Option<&'static str>, pub target_name: Option<&'static str>, pub ambiguous: bool, pub this_adjustment: Option<i32> }

pub static VTABLES: &[VTableInfo] = &[
    VTableInfo { name: "const CRegPropertyBag::`vftable'{for `IPropertyBag'}", rva: 0x3C180, first_slot: 0, slot_count: 6, confidence: "likely" },
    VTableInfo { name: "const CBasePropertyBag::`vftable'{for `IPropertyBag2'}", rva: 0x3C1B0, first_slot: 6, slot_count: 8, confidence: "likely" },
    VTableInfo { name: "const CBasePropertyBag::`vftable'{for `IDataProvider'}", rva: 0x3C1F0, first_slot: 14, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const CBasePropertyBag::`vftable'{for `IPropertyBag'}", rva: 0x3C220, first_slot: 18, slot_count: 6, confidence: "likely" },
    VTableInfo { name: "const Microsoft::WRL::Module<1, class Microsoft::WRL::Details::DefaultModule<1> >::`vftable'", rva: 0x3C5C0, first_slot: 24, slot_count: 12, confidence: "likely" },
    VTableInfo { name: "const Microsoft::WRL::Details::DefaultModule<1>::`vftable'", rva: 0x3C620, first_slot: 36, slot_count: 12, confidence: "likely" },
    VTableInfo { name: "const wil::details::FeatureLogging::`vftable'", rva: 0x3C728, first_slot: 48, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const wistd::__function::__base<bool __cdecl (void *, uint64_t, void *, uint64_t, unsigned int)>::`vftable'", rva: 0x3C748, first_slot: 52, slot_count: 5, confidence: "likely" },
    VTableInfo { name: "const wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>::`vftable'", rva: 0x3C770, first_slot: 57, slot_count: 5, confidence: "likely" },
    VTableInfo { name: "const tip2::details::test_data_interface::`vftable'", rva: 0x3C798, first_slot: 62, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const tip2::details::merged_data<struct _tip_BagsComparisonTest, struct _tip_BagsComparisonTest>::`vftable'", rva: 0x3C7B8, first_slot: 66, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const tip2::details::merged_data<struct _tip_MruLookupTest, struct _tip_MruLookupTest>::`vftable'", rva: 0x3C7D8, first_slot: 70, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const tip2::details::merged_data<struct _tip_PidlNormalizationTest, struct _tip_PidlNormalizationTest>::`vftable'", rva: 0x3C7F8, first_slot: 74, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const CViewStatePropertyBag::`vftable'{for `IPropertyBag'}", rva: 0x3C818, first_slot: 78, slot_count: 6, confidence: "likely" },
    VTableInfo { name: "const CDesktopUpgradePropertyBag::`vftable'{for `IPropertyBag'}", rva: 0x3C848, first_slot: 84, slot_count: 6, confidence: "likely" },
    VTableInfo { name: "const CIniPropertyBag::`vftable'{for `IPropertyBag'}", rva: 0x3C878, first_slot: 90, slot_count: 6, confidence: "likely" },
    VTableInfo { name: "const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<2>, struct ISAXContentHandler, struct ISAXErrorHandler>::`vftable'{for `ISAXContentHandler'}", rva: 0x3C8A8, first_slot: 96, slot_count: 15, confidence: "likely" },
    VTableInfo { name: "const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<2>, struct ISAXContentHandler, struct ISAXErrorHandler>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<2>, 1, struct ISAXErrorHandler>'}", rva: 0x3C920, first_slot: 111, slot_count: 6, confidence: "likely" },
    VTableInfo { name: "const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<2>, struct ISAXContentHandler>::`vftable'", rva: 0x3C950, first_slot: 117, slot_count: 15, confidence: "likely" },
    VTableInfo { name: "const CXMLPropStore::`vftable'{for `IPropertyStore'}", rva: 0x3C9C8, first_slot: 132, slot_count: 8, confidence: "likely" },
    VTableInfo { name: "const CXMLPropStore::`vftable'{for `IObjectWithClassIdentity'}", rva: 0x3CA08, first_slot: 140, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const CXMLPropStore::`vftable'{for `IXMLPropertyStoreInit'}", rva: 0x3CA28, first_slot: 144, slot_count: 4, confidence: "likely" },
    VTableInfo { name: "const CXMLPropStore::`vftable'{for `INamedPropertyStore'}", rva: 0x3CA48, first_slot: 148, slot_count: 7, confidence: "likely" },
    VTableInfo { name: "const CXMLPropStore::`vftable'{for `IInitializeWithStream'}", rva: 0x3CA80, first_slot: 155, slot_count: 5, confidence: "likely" },
    VTableInfo { name: "const CXMLPropStore::`vftable'{for `IPersistPropertyBag'}", rva: 0x3CAA8, first_slot: 160, slot_count: 7, confidence: "likely" },
    VTableInfo { name: "const CXMLPropStoreSaxParser::CStubSaxParser2::`vftable'", rva: 0x3CAE0, first_slot: 167, slot_count: 15, confidence: "likely" },
    VTableInfo { name: "const CXMLPropStoreSaxParser::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<2>, 1, struct ISAXErrorHandler>'}", rva: 0x3CB58, first_slot: 182, slot_count: 6, confidence: "likely" },
    VTableInfo { name: "const CXMLPropStoreSaxParser::`vftable'{for `ISAXContentHandler'}", rva: 0x3CB88, first_slot: 188, slot_count: 15, confidence: "likely" },
];

pub static VTABLE_SLOTS: &[VTableSlot] = &[
    VTableSlot { table_rva: 0x3C180, slot: 0, byte_offset: 0, target_rva: 0xB500, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C180, slot: 1, byte_offset: 8, target_rva: 0x8F70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C180, slot: 2, byte_offset: 16, target_rva: 0x8500, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C180, slot: 3, byte_offset: 24, target_rva: 0x6A30, target_id: Some("?Read@CRegPropertyBag@@UEAAJPEBGPEAUtagVARIANT@@PEAUIErrorLog@@@Z"), target_name: Some("public: virtual long __cdecl CRegPropertyBag::Read(unsigned short const *, struct tagVARIANT *, struct IErrorLog *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C180, slot: 4, byte_offset: 32, target_rva: 0xA1D0, target_id: Some("?Write@CRegPropertyBag@@UEAAJPEBGPEAUtagVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CRegPropertyBag::Write(unsigned short const *, struct tagVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C180, slot: 5, byte_offset: 40, target_rva: 0x8660, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C1B0, slot: 0, byte_offset: 0, target_rva: 0x2BDF0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C1B0, slot: 1, byte_offset: 8, target_rva: 0x2BB60, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C1B0, slot: 2, byte_offset: 16, target_rva: 0x2BFD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C1B0, slot: 3, byte_offset: 24, target_rva: 0x2BB80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C1B0, slot: 4, byte_offset: 32, target_rva: 0x2BB80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C1B0, slot: 5, byte_offset: 40, target_rva: 0x2BB80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C1B0, slot: 6, byte_offset: 48, target_rva: 0x2BB80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C1B0, slot: 7, byte_offset: 56, target_rva: 0x2BB80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C1F0, slot: 0, byte_offset: 0, target_rva: 0x2BE00, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C1F0, slot: 1, byte_offset: 8, target_rva: 0x2BB70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C1F0, slot: 2, byte_offset: 16, target_rva: 0x2BFE0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C1F0, slot: 3, byte_offset: 24, target_rva: 0x2F330, target_id: Some("?ReadData@CBasePropertyBag@@UEAAJHIQEBQEBGQEAUtagVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CBasePropertyBag::ReadData(int, unsigned int, unsigned short const * const * const, struct tagVARIANT * const)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C220, slot: 0, byte_offset: 0, target_rva: 0xB500, target_id: Some("?QueryInterface@CBasePropertyBag@@UEAAJAEBU_GUID@@PEAPEAX@Z"), target_name: Some("public: virtual long __cdecl CBasePropertyBag::QueryInterface(struct _GUID const &, void * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C220, slot: 1, byte_offset: 8, target_rva: 0x8F70, target_id: Some("?AddRef@CBasePropertyBag@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl CBasePropertyBag::AddRef(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C220, slot: 2, byte_offset: 16, target_rva: 0x8500, target_id: Some("?Release@CBasePropertyBag@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl CBasePropertyBag::Release(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C220, slot: 3, byte_offset: 24, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C220, slot: 4, byte_offset: 32, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C220, slot: 5, byte_offset: 40, target_rva: 0x2BB10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C5C0, slot: 0, byte_offset: 0, target_rva: 0x29190, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C5C0, slot: 1, byte_offset: 8, target_rva: 0x293D0, target_id: Some("?IncrementObjectCount@?$Module@$00V?$DefaultModule@$00@Details@WRL@Microsoft@@@WRL@Microsoft@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl Microsoft::WRL::Module<1, class Microsoft::WRL::Details::DefaultModule<1> >::IncrementObjectCount(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C5C0, slot: 2, byte_offset: 16, target_rva: 0x291D0, target_id: Some("?DecrementObjectCount@?$Module@$00V?$DefaultModule@$00@Details@WRL@Microsoft@@@WRL@Microsoft@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl Microsoft::WRL::Module<1, class Microsoft::WRL::Details::DefaultModule<1> >::DecrementObjectCount(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C5C0, slot: 3, byte_offset: 24, target_rva: 0xFE80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C5C0, slot: 4, byte_offset: 32, target_rva: 0x8F60, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C5C0, slot: 5, byte_offset: 40, target_rva: 0x293C0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C5C0, slot: 6, byte_offset: 48, target_rva: 0xFE90, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C5C0, slot: 7, byte_offset: 56, target_rva: 0x293B0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C5C0, slot: 8, byte_offset: 64, target_rva: 0x29420, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C5C0, slot: 9, byte_offset: 72, target_rva: 0x29420, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C5C0, slot: 10, byte_offset: 80, target_rva: 0x29420, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C5C0, slot: 11, byte_offset: 88, target_rva: 0x29420, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C620, slot: 0, byte_offset: 0, target_rva: 0x9970, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C620, slot: 1, byte_offset: 8, target_rva: 0x293D0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C620, slot: 2, byte_offset: 16, target_rva: 0x291D0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C620, slot: 3, byte_offset: 24, target_rva: 0xFE80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C620, slot: 4, byte_offset: 32, target_rva: 0x8F60, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C620, slot: 5, byte_offset: 40, target_rva: 0x293C0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C620, slot: 6, byte_offset: 48, target_rva: 0xFE90, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C620, slot: 7, byte_offset: 56, target_rva: 0x293B0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C620, slot: 8, byte_offset: 64, target_rva: 0x29420, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C620, slot: 9, byte_offset: 72, target_rva: 0x29420, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C620, slot: 10, byte_offset: 80, target_rva: 0x29420, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C620, slot: 11, byte_offset: 88, target_rva: 0x29420, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C728, slot: 0, byte_offset: 0, target_rva: 0x1C5D0, target_id: Some("?NotifyFailure@TraceLoggingProvider@wil@@EEAA_NAEBUFailureInfo@2@@Z"), target_name: Some("private: virtual bool __cdecl wil::TraceLoggingProvider::NotifyFailure(struct wil::FailureInfo const &)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C728, slot: 1, byte_offset: 8, target_rva: 0x1C120, target_id: Some("?Initialize@TraceLoggingProvider@wil@@MEAAXXZ"), target_name: Some("protected: virtual void __cdecl wil::TraceLoggingProvider::Initialize(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C728, slot: 2, byte_offset: 16, target_rva: 0x1C670, target_id: Some("?OnErrorReported@TraceLoggingProvider@wil@@MEAAX_NAEBUFailureInfo@2@@Z"), target_name: Some("protected: virtual void __cdecl wil::TraceLoggingProvider::OnErrorReported(bool, struct wil::FailureInfo const &)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C728, slot: 3, byte_offset: 24, target_rva: 0x1B670, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C748, slot: 0, byte_offset: 0, target_rva: 0x1B640, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C748, slot: 1, byte_offset: 8, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C748, slot: 2, byte_offset: 16, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C748, slot: 3, byte_offset: 24, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C748, slot: 4, byte_offset: 32, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C770, slot: 0, byte_offset: 0, target_rva: 0x1B640, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C770, slot: 1, byte_offset: 8, target_rva: 0x1E490, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C770, slot: 2, byte_offset: 16, target_rva: 0x1E490, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C770, slot: 3, byte_offset: 24, target_rva: 0x1C120, target_id: Some("?destroy@?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAAXXZ"), target_name: Some("public: virtual void __cdecl wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>::destroy(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C770, slot: 4, byte_offset: 32, target_rva: 0x1B5D0, target_id: Some("??R?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAA_N$$QEAPEAX$$QEA_K01$$QEAI@Z"), target_name: Some("public: virtual bool __cdecl wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>::operator()(void * &&, uint64_t &&, void * &&, uint64_t &&, unsigned int &&)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C798, slot: 0, byte_offset: 0, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C798, slot: 1, byte_offset: 8, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C798, slot: 2, byte_offset: 16, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C798, slot: 3, byte_offset: 24, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C7B8, slot: 0, byte_offset: 0, target_rva: 0x2CE10, target_id: Some("?evaluate@?$merged_data@U_tip_BagsComparisonTest@@U1@@details@tip2@@EEAAXXZ"), target_name: Some("private: virtual void __cdecl tip2::details::merged_data<struct _tip_BagsComparisonTest, struct _tip_BagsComparisonTest>::evaluate(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C7B8, slot: 1, byte_offset: 8, target_rva: 0x2DFF0, target_id: Some("?serialize@?$merged_data@U_tip_BagsComparisonTest@@U1@@details@tip2@@EEAAXAEAVoutput_archive@tson@@W4serialize_options@23@@Z"), target_name: Some("private: virtual void __cdecl tip2::details::merged_data<struct _tip_BagsComparisonTest, struct _tip_BagsComparisonTest>::serialize(class tson::output_archive &, enum tip2::details::serialize_options)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C7B8, slot: 2, byte_offset: 16, target_rva: 0x2CA80, target_id: Some("?deserialize@?$merged_data@U_tip_BagsComparisonTest@@U1@@details@tip2@@EEAAXAEAVinput_archive@tson@@@Z"), target_name: Some("private: virtual void __cdecl tip2::details::merged_data<struct _tip_BagsComparisonTest, struct _tip_BagsComparisonTest>::deserialize(class tson::input_archive &)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C7B8, slot: 3, byte_offset: 24, target_rva: 0x1C120, target_id: Some("?on_result@?$merged_data@U_tip_BagsComparisonTest@@U1@@details@tip2@@EEAAXAEBUTipReportingInfo@@@Z"), target_name: Some("private: virtual void __cdecl tip2::details::merged_data<struct _tip_BagsComparisonTest, struct _tip_BagsComparisonTest>::on_result(struct TipReportingInfo const &)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C7D8, slot: 0, byte_offset: 0, target_rva: 0x2CE30, target_id: Some("?evaluate@?$merged_data@U_tip_MruLookupTest@@U1@@details@tip2@@EEAAXXZ"), target_name: Some("private: virtual void __cdecl tip2::details::merged_data<struct _tip_MruLookupTest, struct _tip_MruLookupTest>::evaluate(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C7D8, slot: 1, byte_offset: 8, target_rva: 0x2E090, target_id: Some("?serialize@?$merged_data@U_tip_MruLookupTest@@U1@@details@tip2@@EEAAXAEAVoutput_archive@tson@@W4serialize_options@23@@Z"), target_name: Some("private: virtual void __cdecl tip2::details::merged_data<struct _tip_MruLookupTest, struct _tip_MruLookupTest>::serialize(class tson::output_archive &, enum tip2::details::serialize_options)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C7D8, slot: 2, byte_offset: 16, target_rva: 0x2CAC0, target_id: Some("?deserialize@?$merged_data@U_tip_MruLookupTest@@U1@@details@tip2@@EEAAXAEAVinput_archive@tson@@@Z"), target_name: Some("private: virtual void __cdecl tip2::details::merged_data<struct _tip_MruLookupTest, struct _tip_MruLookupTest>::deserialize(class tson::input_archive &)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C7D8, slot: 3, byte_offset: 24, target_rva: 0x1C120, target_id: Some("?on_result@?$merged_data@U_tip_MruLookupTest@@U1@@details@tip2@@EEAAXAEBUTipReportingInfo@@@Z"), target_name: Some("private: virtual void __cdecl tip2::details::merged_data<struct _tip_MruLookupTest, struct _tip_MruLookupTest>::on_result(struct TipReportingInfo const &)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C7F8, slot: 0, byte_offset: 0, target_rva: 0x2CE50, target_id: Some("?evaluate@?$merged_data@U_tip_PidlNormalizationTest@@U1@@details@tip2@@EEAAXXZ"), target_name: Some("private: virtual void __cdecl tip2::details::merged_data<struct _tip_PidlNormalizationTest, struct _tip_PidlNormalizationTest>::evaluate(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C7F8, slot: 1, byte_offset: 8, target_rva: 0x2E130, target_id: Some("?serialize@?$merged_data@U_tip_PidlNormalizationTest@@U1@@details@tip2@@EEAAXAEAVoutput_archive@tson@@W4serialize_options@23@@Z"), target_name: Some("private: virtual void __cdecl tip2::details::merged_data<struct _tip_PidlNormalizationTest, struct _tip_PidlNormalizationTest>::serialize(class tson::output_archive &, enum tip2::details::serialize_options)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C7F8, slot: 2, byte_offset: 16, target_rva: 0x2CB60, target_id: Some("?deserialize@?$merged_data@U_tip_PidlNormalizationTest@@U1@@details@tip2@@EEAAXAEAVinput_archive@tson@@@Z"), target_name: Some("private: virtual void __cdecl tip2::details::merged_data<struct _tip_PidlNormalizationTest, struct _tip_PidlNormalizationTest>::deserialize(class tson::input_archive &)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C7F8, slot: 3, byte_offset: 24, target_rva: 0x1C120, target_id: Some("?on_result@?$merged_data@U_tip_PidlNormalizationTest@@U1@@details@tip2@@EEAAXAEBUTipReportingInfo@@@Z"), target_name: Some("private: virtual void __cdecl tip2::details::merged_data<struct _tip_PidlNormalizationTest, struct _tip_PidlNormalizationTest>::on_result(struct TipReportingInfo const &)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C818, slot: 0, byte_offset: 0, target_rva: 0xB500, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C818, slot: 1, byte_offset: 8, target_rva: 0x8F70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C818, slot: 2, byte_offset: 16, target_rva: 0x8500, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C818, slot: 3, byte_offset: 24, target_rva: 0x6170, target_id: Some("?Read@CViewStatePropertyBag@@UEAAJPEBGPEAUtagVARIANT@@PEAUIErrorLog@@@Z"), target_name: Some("public: virtual long __cdecl CViewStatePropertyBag::Read(unsigned short const *, struct tagVARIANT *, struct IErrorLog *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C818, slot: 4, byte_offset: 32, target_rva: 0x4B10, target_id: Some("?Write@CViewStatePropertyBag@@UEAAJPEBGPEAUtagVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CViewStatePropertyBag::Write(unsigned short const *, struct tagVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C818, slot: 5, byte_offset: 40, target_rva: 0xF710, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C848, slot: 0, byte_offset: 0, target_rva: 0xB500, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C848, slot: 1, byte_offset: 8, target_rva: 0x8F70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C848, slot: 2, byte_offset: 16, target_rva: 0x8500, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C848, slot: 3, byte_offset: 24, target_rva: 0x2BE10, target_id: Some("?Read@CDesktopUpgradePropertyBag@@UEAAJPEBGPEAUtagVARIANT@@PEAUIErrorLog@@@Z"), target_name: Some("public: virtual long __cdecl CDesktopUpgradePropertyBag::Read(unsigned short const *, struct tagVARIANT *, struct IErrorLog *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C848, slot: 4, byte_offset: 32, target_rva: 0x2BB80, target_id: Some("?Write@CDesktopUpgradePropertyBag@@UEAAJPEBGPEAUtagVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CDesktopUpgradePropertyBag::Write(unsigned short const *, struct tagVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C848, slot: 5, byte_offset: 40, target_rva: 0x2BB10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C878, slot: 0, byte_offset: 0, target_rva: 0xB500, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C878, slot: 1, byte_offset: 8, target_rva: 0x8F70, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C878, slot: 2, byte_offset: 16, target_rva: 0x8500, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C878, slot: 3, byte_offset: 24, target_rva: 0x2EE10, target_id: Some("?Read@CIniPropertyBag@@UEAAJPEBGPEAUtagVARIANT@@PEAUIErrorLog@@@Z"), target_name: Some("public: virtual long __cdecl CIniPropertyBag::Read(unsigned short const *, struct tagVARIANT *, struct IErrorLog *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C878, slot: 4, byte_offset: 32, target_rva: 0x2EFF0, target_id: Some("?Write@CIniPropertyBag@@UEAAJPEBGPEAUtagVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CIniPropertyBag::Write(unsigned short const *, struct tagVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C878, slot: 5, byte_offset: 40, target_rva: 0x2EDD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 0, byte_offset: 0, target_rva: 0x31E40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 1, byte_offset: 8, target_rva: 0x30730, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 2, byte_offset: 16, target_rva: 0x31FB0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 3, byte_offset: 24, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 4, byte_offset: 32, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 5, byte_offset: 40, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 6, byte_offset: 48, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 7, byte_offset: 56, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 8, byte_offset: 64, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 9, byte_offset: 72, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 10, byte_offset: 80, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 11, byte_offset: 88, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 12, byte_offset: 96, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 13, byte_offset: 104, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C8A8, slot: 14, byte_offset: 112, target_rva: 0x30610, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C920, slot: 0, byte_offset: 0, target_rva: 0x31ED0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C920, slot: 1, byte_offset: 8, target_rva: 0x30740, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C920, slot: 2, byte_offset: 16, target_rva: 0x32010, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C920, slot: 3, byte_offset: 24, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C920, slot: 4, byte_offset: 32, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C920, slot: 5, byte_offset: 40, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 0, byte_offset: 0, target_rva: 0x31DD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 1, byte_offset: 8, target_rva: 0x30720, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 2, byte_offset: 16, target_rva: 0x31F50, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 3, byte_offset: 24, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 4, byte_offset: 32, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 5, byte_offset: 40, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 6, byte_offset: 48, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 7, byte_offset: 56, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 8, byte_offset: 64, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 9, byte_offset: 72, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 10, byte_offset: 80, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 11, byte_offset: 88, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 12, byte_offset: 96, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 13, byte_offset: 104, target_rva: 0x38E80, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C950, slot: 14, byte_offset: 112, target_rva: 0x305E0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C9C8, slot: 0, byte_offset: 0, target_rva: 0x31F30, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C9C8, slot: 1, byte_offset: 8, target_rva: 0x307A0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C9C8, slot: 2, byte_offset: 16, target_rva: 0x32090, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3C9C8, slot: 3, byte_offset: 24, target_rva: 0x30F00, target_id: Some("?GetCount@CXMLPropStore@@UEAAJPEAK@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::GetCount(unsigned long *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C9C8, slot: 4, byte_offset: 32, target_rva: 0x30AE0, target_id: Some("?GetAt@CXMLPropStore@@UEAAJKPEAU_tagpropertykey@@@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::GetAt(unsigned long, struct _tagpropertykey *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C9C8, slot: 5, byte_offset: 40, target_rva: 0xE7C0, target_id: Some("?GetValue@CXMLPropStore@@UEAAJAEBU_tagpropertykey@@PEAUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::GetValue(struct _tagpropertykey const &, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C9C8, slot: 6, byte_offset: 48, target_rva: 0x32AE0, target_id: Some("?SetValue@CXMLPropStore@@UEAAJAEBU_tagpropertykey@@AEBUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::SetValue(struct _tagpropertykey const &, struct tagPROPVARIANT const &)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3C9C8, slot: 7, byte_offset: 56, target_rva: 0x30980, target_id: Some("?Commit@CXMLPropStore@@UEAAJXZ"), target_name: Some("public: virtual long __cdecl CXMLPropStore::Commit(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA08, slot: 0, byte_offset: 0, target_rva: 0x31F40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA08, slot: 1, byte_offset: 8, target_rva: 0x307B0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA08, slot: 2, byte_offset: 16, target_rva: 0x320A0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA08, slot: 3, byte_offset: 24, target_rva: 0x30ED0, target_id: Some("?GetClassIdentity@CXMLPropStore@@UEAAJPEAPEAG@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::GetClassIdentity(unsigned short * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA28, slot: 0, byte_offset: 0, target_rva: 0x31F10, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA28, slot: 1, byte_offset: 8, target_rva: 0x30780, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA28, slot: 2, byte_offset: 16, target_rva: 0x32070, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA28, slot: 3, byte_offset: 24, target_rva: 0x316A0, target_id: Some("?Initialize@CXMLPropStore@@UEAAJPEAUIXMLDOMNode@@K@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::Initialize(struct IXMLDOMNode *, unsigned long)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA48, slot: 0, byte_offset: 0, target_rva: 0x31F20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA48, slot: 1, byte_offset: 8, target_rva: 0x30790, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA48, slot: 2, byte_offset: 16, target_rva: 0x32080, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA48, slot: 3, byte_offset: 24, target_rva: 0x313B0, target_id: Some("?GetNamedValue@CXMLPropStore@@UEAAJPEBGPEAUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::GetNamedValue(unsigned short const *, struct tagPROPVARIANT *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA48, slot: 4, byte_offset: 32, target_rva: 0x32570, target_id: Some("?SetNamedValue@CXMLPropStore@@UEAAJPEBGAEBUtagPROPVARIANT@@@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::SetNamedValue(unsigned short const *, struct tagPROPVARIANT const &)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA48, slot: 5, byte_offset: 40, target_rva: 0x312F0, target_id: Some("?GetNameCount@CXMLPropStore@@UEAAJPEAK@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::GetNameCount(unsigned long *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA48, slot: 6, byte_offset: 48, target_rva: 0x311A0, target_id: Some("?GetNameAt@CXMLPropStore@@UEAAJKPEAPEAG@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::GetNameAt(unsigned long, unsigned short * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA80, slot: 0, byte_offset: 0, target_rva: 0x31EE0, target_id: Some("?QueryInterface@CXMLPropStore@@UEAAJAEBU_GUID@@PEAPEAX@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::QueryInterface(struct _GUID const &, void * *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA80, slot: 1, byte_offset: 8, target_rva: 0x30750, target_id: Some("?AddRef@CXMLPropStore@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl CXMLPropStore::AddRef(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA80, slot: 2, byte_offset: 16, target_rva: 0x32020, target_id: Some("?Release@CXMLPropStore@@UEAAKXZ"), target_name: Some("public: virtual unsigned long __cdecl CXMLPropStore::Release(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA80, slot: 3, byte_offset: 24, target_rva: 0x31600, target_id: Some("?Initialize@CXMLPropStore@@UEAAJPEAUIStream@@K@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::Initialize(struct IStream *, unsigned long)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CA80, slot: 4, byte_offset: 32, target_rva: 0x30680, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAA8, slot: 0, byte_offset: 0, target_rva: 0x31F00, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAA8, slot: 1, byte_offset: 8, target_rva: 0x30770, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAA8, slot: 2, byte_offset: 16, target_rva: 0x32060, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAA8, slot: 3, byte_offset: 24, target_rva: 0x30EB0, target_id: Some("?GetClassID@CXMLPropStore@@UEAAJPEAU_GUID@@@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::GetClassID(struct _GUID *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAA8, slot: 4, byte_offset: 32, target_rva: 0x26D20, target_id: Some("?InitNew@CXMLPropStore@@UEAAJXZ"), target_name: Some("public: virtual long __cdecl CXMLPropStore::InitNew(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAA8, slot: 5, byte_offset: 40, target_rva: 0x31750, target_id: Some("?Load@CXMLPropStore@@UEAAJPEAUIPropertyBag@@PEAUIErrorLog@@@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::Load(struct IPropertyBag *, struct IErrorLog *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAA8, slot: 6, byte_offset: 48, target_rva: 0x32560, target_id: Some("?Save@CXMLPropStore@@UEAAJPEAUIPropertyBag@@HH@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStore::Save(struct IPropertyBag *, int, int)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 0, byte_offset: 0, target_rva: 0x31DD0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 1, byte_offset: 8, target_rva: 0x30720, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 2, byte_offset: 16, target_rva: 0x31F50, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 3, byte_offset: 24, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 4, byte_offset: 32, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 5, byte_offset: 40, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 6, byte_offset: 48, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 7, byte_offset: 56, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 8, byte_offset: 64, target_rva: 0x370B0, target_id: Some("?startElement@CStubSaxParser2@CXMLPropStoreSaxParser@@UEAAJPEBGH0H0HPEAUISAXAttributes@@@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStoreSaxParser::CStubSaxParser2::startElement(unsigned short const *, int, unsigned short const *, int, unsigned short const *, int, struct ISAXAttributes *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 9, byte_offset: 72, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 10, byte_offset: 80, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 11, byte_offset: 88, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 12, byte_offset: 96, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 13, byte_offset: 104, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CAE0, slot: 14, byte_offset: 112, target_rva: 0x30640, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB58, slot: 0, byte_offset: 0, target_rva: 0x31ED0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB58, slot: 1, byte_offset: 8, target_rva: 0x30740, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB58, slot: 2, byte_offset: 16, target_rva: 0x32010, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB58, slot: 3, byte_offset: 24, target_rva: 0x36F60, target_id: Some("?error@CXMLPropStoreSaxParser@@UEAAJPEAUISAXLocator@@PEBGJ@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStoreSaxParser::error(struct ISAXLocator *, unsigned short const *, long)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB58, slot: 4, byte_offset: 32, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB58, slot: 5, byte_offset: 40, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 0, byte_offset: 0, target_rva: 0x31E40, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 1, byte_offset: 8, target_rva: 0x30730, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 2, byte_offset: 16, target_rva: 0x31FB0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 3, byte_offset: 24, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 4, byte_offset: 32, target_rva: 0x37030, target_id: Some("?startDocument@CXMLPropStoreSaxParser@@UEAAJXZ"), target_name: Some("public: virtual long __cdecl CXMLPropStoreSaxParser::startDocument(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 5, byte_offset: 40, target_rva: 0x36840, target_id: Some("?endDocument@CXMLPropStoreSaxParser@@UEAAJXZ"), target_name: Some("public: virtual long __cdecl CXMLPropStoreSaxParser::endDocument(void)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 6, byte_offset: 48, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 7, byte_offset: 56, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 8, byte_offset: 64, target_rva: 0x37150, target_id: Some("?startElement@CXMLPropStoreSaxParser@@UEAAJPEBGH0H0HPEAUISAXAttributes@@@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStoreSaxParser::startElement(unsigned short const *, int, unsigned short const *, int, unsigned short const *, int, struct ISAXAttributes *)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 9, byte_offset: 72, target_rva: 0x36860, target_id: Some("?endElement@CXMLPropStoreSaxParser@@UEAAJPEBGH0H0H@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStoreSaxParser::endElement(unsigned short const *, int, unsigned short const *, int, unsigned short const *, int)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 10, byte_offset: 80, target_rva: 0x36630, target_id: Some("?characters@CXMLPropStoreSaxParser@@UEAAJPEBGH@Z"), target_name: Some("public: virtual long __cdecl CXMLPropStoreSaxParser::characters(unsigned short const *, int)"), ambiguous: false, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 11, byte_offset: 88, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 12, byte_offset: 96, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 13, byte_offset: 104, target_rva: 0x26D20, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
    VTableSlot { table_rva: 0x3CB88, slot: 14, byte_offset: 112, target_rva: 0x306C0, target_id: None, target_name: None, ambiguous: true, this_adjustment: None },
];

/// Reads a raw function pointer from an object's primary vftable.
///
/// # Safety
/// `object` must point to a live object with a readable primary vftable,
/// and `slot` must be valid for that concrete object. This function does
/// not invent or transmute a callable signature.
pub unsafe fn raw_object_slot(object: *const c_void, slot: usize) -> Option<*const ()> {
if object.is_null() { return None; }
let table = unsafe { *(object.cast::<*const *const ()>()) };
if table.is_null() { return None; }
let target = unsafe { *table.add(slot) };
(!target.is_null()).then_some(target)
}
